; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; ESP32-S3 + ST7789 2.0" TFT + HLK-LD2450 Radar

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM10
upload_speed = 460800
upload_flags =
    --no-stub

; Serial mapped to UART0 (CH343 / COM10) + compiler speed optimizations
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -O2
    -ffast-math

lib_deps = 
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    adafruit/Adafruit NeoPixel @ ^1.12.0
